apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./sa.k8s.yaml
  - ./deploy.k8s.yaml
  - ./svc.k8s.yaml
commonLabels:
  app.kubernetes.io/name: crd-json-schema-server
images:
  - name: jeewangue/crd-json-schema-server
    newTag: latest
