apiVersion: v1
kind: ServiceAccount
metadata:
  name: crd-json-schema-server

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crd-json-schema-server
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crd-json-schema-server
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: crd-json-schema-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-json-schema-server
